# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
breweries = Brewery.create([
  { name: 'Living the Dream', address_city: 'Littleton', address_state: 'Colorado', address_zip: '80125', description: 'We are a dog friendly brewery & taproom located in Highlands Ranch, Colorado.', email: 'info@livingthedream.com', phone: '(303) 284-9585', website: 'http://livingthedreambrewing.com', is_restaurant: false, remote_schedule_endpoint: "http://livingthedreambrewing.com/events/?view=calendar&month=||MONTH-YYYY||", remote_endpoint_requires_date: true, schedule_scan_pattern: '\|\|*.+\|\|', schedule_gsub_pattern: '\|\|MONTH-YYYY\|\|' },
  { name: 'Grist Brewing Company', address_city: 'Highlands Ranch', address_state: 'Colorado', address_zip: '80129', description: 'Science balanced with creativity!', email: 'info@gristbrewingcompany.com', phone: '(720) 360-4782', website: 'http://www.gristbrewingcompany.com', is_restaurant: false, remote_schedule_endpoint: "https://www.gristbrewingcompany.com/events/?date=||M/D/YYYY||", remote_endpoint_requires_date: true, schedule_scan_pattern: '\|\|*.+\|\|', schedule_gsub_pattern: '\|\|M\/D\/YYYY\|\|' },
  { name: 'Thirty Eight State Brewing Company', address_city: 'Littleton', address_state: 'Colorado', address_zip: '80122', description: 'A brewery that makes beer to put in your mouth.', email: 'info@38statebrew.com', phone: '(720) 638-3678', website: 'http://38statebrew.com', is_restaurant: false, remote_schedule_endpoint: "http://38statebrew.com/wp-admin/admin-ajax.php?action=spiderbigcalendar_list&calendar=1&date=||YYYY-MM||", remote_endpoint_requires_date: true, schedule_scan_pattern: '\|\|*.+\|\|', schedule_gsub_pattern: '\|\|YYYY-MM\|\|' },
  { name: 'Lone Tree Brewing Company', address_city: 'Lone Tree', address_state: 'Colorado', address_zip: '80124', description: 'A brewery that makes beer to put in your mouth.', email: 'info@lonetreebrewingco.com', phone: '(303) 792-5822', website: 'http://lonetreebrewingco.com', is_restaurant: false, remote_schedule_endpoint: "http://lonetreebrewingco.com/events/today/", remote_endpoint_requires_date: false },
  { name: 'Resolute Brewing Company', address_city: 'Centennial', address_state: 'Colorado', address_zip: '80112', description: 'Community, Craft, Culture', email: 'cheers@resolutebrewingco.com', phone: '(720) 722-1238', website: 'http://resolutebrewingco.com', is_restaurant: false, remote_schedule_endpoint: "http://resolutebrewingco.com/event-calendar/", remote_endpoint_requires_date: false },
  ])
