export const LOAD_BREWERIES_SUCCESS = 'LOAD_BREWERIES_SUCCESS';
export const LOAD_FOOD_TRUCKS_SUCCESS = 'LOAD_FOOD_TRUCKS_SUCCESS';
export const LOAD_FOOD_TRUCK_CALENDARS_SUCCESS = 'LOAD_FOOD_TRUCK_CALENDARS_SUCCESS';
